"""product variants and orderitem variant_name

Revision ID: 76bea019f3d0
Revises: 691c604a5c6a
Create Date: 2026-05-04 12:57:54.601033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76bea019f3d0'
down_revision: Union[str, Sequence[str], None] = '691c604a5c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productvariant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price_adjustment', sa.Float(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productvariant_product_id'), 'productvariant', ['product_id'], unique=False)
    op.add_column('orderitem', sa.Column('variant_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orderitem', 'variant_name')
    op.drop_index(op.f('ix_productvariant_product_id'), table_name='productvariant')
    op.drop_table('productvariant')
    # ### end Alembic commands ###
