"""add product image_url

Revision ID: cda2b39dd99f
Revises: b04f8e2a1c3d
Create Date: 2026-04-30 18:28:37.345246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda2b39dd99f'
down_revision: Union[str, Sequence[str], None] = 'b04f8e2a1c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'status',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.Enum('pending', 'processing', 'shipped', 'delivered', 'cancelled', name='orderstatus', native_enum=False),
               existing_nullable=False)
    op.add_column('product', sa.Column('image_url', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_url')
    op.alter_column('order', 'status',
               existing_type=sa.Enum('pending', 'processing', 'shipped', 'delivered', 'cancelled', name='orderstatus', native_enum=False),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    # ### end Alembic commands ###
