"""reviews ratings reactions

Revision ID: ef39ef751e5f
Revises: a23dbbdd319a
Create Date: 2026-04-30 16:57:32.827538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef39ef751e5f'
down_revision: Union[str, Sequence[str], None] = 'a23dbbdd319a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('is_verified_purchase', sa.Boolean(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_product_id'), 'review', ['product_id'], unique=False)
    op.create_index(op.f('ix_review_user_id'), 'review', ['user_id'], unique=False)
    op.create_table('reviewreaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_like', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'user_id', name='uq_review_reaction_user')
    )
    op.create_index(op.f('ix_reviewreaction_review_id'), 'reviewreaction', ['review_id'], unique=False)
    op.create_index(op.f('ix_reviewreaction_user_id'), 'reviewreaction', ['user_id'], unique=False)
    # NOT NULL without default fails on existing rows; server_default backfills them.
    op.add_column(
        'product',
        sa.Column(
            'average_rating',
            sa.Numeric(precision=3, scale=2),
            nullable=False,
            server_default=sa.text('0'),
        ),
    )
    op.add_column(
        'product',
        sa.Column(
            'total_reviews',
            sa.Integer(),
            nullable=False,
            server_default=sa.text('0'),
        ),
    )
    op.alter_column('product', 'average_rating', server_default=None)
    op.alter_column('product', 'total_reviews', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'total_reviews')
    op.drop_column('product', 'average_rating')
    op.drop_index(op.f('ix_reviewreaction_user_id'), table_name='reviewreaction')
    op.drop_index(op.f('ix_reviewreaction_review_id'), table_name='reviewreaction')
    op.drop_table('reviewreaction')
    op.drop_index(op.f('ix_review_user_id'), table_name='review')
    op.drop_index(op.f('ix_review_product_id'), table_name='review')
    op.drop_table('review')
    # ### end Alembic commands ###
